[build]
  command = "yarn build"
  publish = "public"

[build.environment]
  NODE_VERSION = "14.21.3"
  NPM_FLAGS = "--version"
  YARN_VERSION = "1.22.22"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 