[build]
  command = "CI=false yarn build"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"
  YARN_FLAGS = "--production=false"
  YARN_VERSION = "1.22.22"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 